### ISSUE TITLE
Execution related 

### ISSUE THREAD

**Issue by rajeshchaudhary121** [MMorafah/FLIS#4]
how to execute this code on google colab?

please provide the procedure as I am unable to execute the code. 

and if it get executes it returns
**MODEL: lenet5, Dataset: cifar10
not supported yet**

**Comment by MMorafah** [comment]
Hello,

I cannot help much on how to execute the code on google colab since many functions are in separate folders and .py files. You may try to put the whole source code in the google colab and or search how to clone a repo in google colab and run it. You may also try to add all the functions in only one file, this will most likely work on google colab.

Regards,
Mahdi

**Comment by zhanglan-333** [comment]
Hello，
I also met this problem on python，how can i solve this question?

**Comment by MMorafah** [comment]
Hello, 

“simple-cnn” is the same as lenet5. We have also put the scripts to run the code. Regarding the procedure on how to run the code on Google colab, I cannot help much. However, there should be tutorials on how to clone and run a Github repository on Google colab.
